create nest.js project structure
caju-code/poupapig-backend pull request #5
Opened 2024-11-12 03:00 UTC by wagnermsp

Create new nest.js project structure using standard "new" command following the instructions below:
https://docs.nestjs.com/cli/overview

It was necessary to delete a .git directory that was automatically created by this command

Should I  delete the ReadMe file that was also created since we already have one?

2024-11-18 13:07 UTC, fegvilela requested changes

2024-11-18 13:07 UTC, fegvilela commented on poupapig-backend-nestjs/README.md
> +## Project setup
I think you can use these sections to complement the former README|

I mean, the sections that contain any kind of `npm` command :)

Then, delete the file in this PR

2024-11-18 13:07 UTC, fegvilela commented on poupapig-backend-nestjs/.gitignore
> +/dist
same thing here, copy this content and use it in the former .gitignore, then delete this file in this PR

2024-11-18 13:07 UTC, fegvilela commented on poupapig-backend-nestjs/package.json
> +  "license": "UNLICENSED",
```suggestion
  "license": "MIT",
```

2024-11-18 13:07 UTC, fegvilela commented on poupapig-backend-nestjs/package.json
> +  "private": true,
```suggestion
  "private": false,
```

2024-11-20 02:13 UTC, wagnermsp commented on poupapig-backend-nestjs/package.json
> +  "private": true,
I didn't even opened these files. My bad.

2024-11-21 13:34 UTC, fegvilela approved these changes
🤑🐽

2024-11-21 13:34 UTC, fegvilela submitted a review, later dismissed
🤑🐽

2024-11-22 19:13 UTC, fegvilela approved these changes

2024-11-22 19:14 UTC, merged